/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pis;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import re.dao.DAOException;
import re.dao.DAOManager;
import re.dao.bd.OracleDaoManager;
import reg.modelo.Empleado;
import reg.modelo.Factura;
import reg.modelo.Login;
import rojerusan.RSPanelsSlider;
/**
 *
 * @author Astaroth
 */
public class Empleado2 extends javax.swing.JDialog {

    private Login login;
    private DAOManager manager;
    private Empleado empleado;
    private Factura factura;
    private int cod;
    private String user;
    
    public Empleado2(java.awt.Frame parent, boolean modal,DAOManager manager) throws DAOException {
        super(parent, modal);
        initComponents();
        this.manager = manager;
        this.setResizable(false);
        datos();
        rsutilities.RSUtilities.setCentrarVentana(this);
        
    }
    public Empleado2(java.awt.Frame parent, boolean modal, DAOManager manager, int cod, String user) throws DAOException {
        super(parent, modal);
        initComponents();
        this.manager = manager;
        this.cod = cod;
        this.user = user;
        this.setResizable(false);
        rsutilities.RSUtilities.setCentrarVentana(this);
        datos();
    }
    private Empleado getEmpleadoSeleccionado() throws DAOException {
        return manager.getEmpleadoDAO().obtener(cod);
    }

    private Login getLoginSeleccionado() throws DAOException {
        return manager.getLoginDAO().obtenerUser(user);
    }
    
    private Factura getfacturaSeleccionado() throws DAOException {
        return manager.getFacturaDAO().obtenerUser(user);
    }
    
    public void datos(){
        
        try {
            Empleado em = getEmpleadoSeleccionado();
            Login lg = getLoginSeleccionado();
            pnPerfil1.setEmpleado(em);
            pnPerfil1.setLogin(lg);
            pnPerfil1.setVentana2(this);
            pnPerfil1.setManager(manager);
            pnPerfil1.setEditable(false);
            pnPerfil1.loadData();
        } catch (DAOException ex) {
            Logger.getLogger(Empleado2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public Factura getFactura() {
        return factura;
    }

    public void setFactura(Factura factura) {
        this.factura = factura;
    }

    public JLabel getjLbnombreemp() {
        return jLbnombreemp;
    }

    public void setjLbnombreemp(JLabel jLbnombreemp) {
        this.jLbnombreemp = jLbnombreemp;
    }

    public JLabel getjLbrango() {
        return jLbrango;
    }

    public void setjLbrango(JLabel jLbrango) {
        this.jLbrango = jLbrango;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jBreportes = new rojeru_san.RSButton();
        jBventas = new rojeru_san.RSButton();
        jBActividades = new rojeru_san.RSButton();
        jBperfil = new rojeru_san.RSButton();
        jLbrango = new javax.swing.JLabel();
        jLbnombreemp = new javax.swing.JLabel();
        rSPanelCircle2 = new rojeru_san.rspanel.RSPanelCircle();
        rSPanelGradiente1 = new rspanelgradiente.RSPanelGradiente();
        jBtcerrarsesion = new rojeru_san.RSButton();
        rSPanelsSlider1 = new rojerusan.RSPanelsSlider();
        pnl1 = new javax.swing.JPanel();
        pnPerfil1 = new pis.PnPerfil();
        pnl3 = new javax.swing.JPanel();
        pnVentas1 = new pis.PnVentas();
        pnl4 = new javax.swing.JPanel();
        jPregistros2 = new pis.jPregistros();
        pnl2 = new javax.swing.JPanel();
        jPactividades1 = new pis.jPactividades();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(38, 38, 38));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBreportes.setBackground(new java.awt.Color(0, 0, 0));
        jBreportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/image (1).png"))); // NOI18N
        jBreportes.setText(" Reportes");
        jBreportes.setColorHover(new java.awt.Color(43, 43, 43));
        jBreportes.setColorText(new java.awt.Color(154, 159, 168));
        jBreportes.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        jBreportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBreportesActionPerformed(evt);
            }
        });
        jPanel2.add(jBreportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 382, 194, -1));

        jBventas.setBackground(new java.awt.Color(0, 0, 0));
        jBventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Ventas.png"))); // NOI18N
        jBventas.setText("     Ventas");
        jBventas.setColorHover(new java.awt.Color(43, 43, 43));
        jBventas.setColorText(new java.awt.Color(154, 159, 168));
        jBventas.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        jBventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBventasActionPerformed(evt);
            }
        });
        jPanel2.add(jBventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 336, 190, -1));

        jBActividades.setBackground(new java.awt.Color(0, 0, 0));
        jBActividades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Actividades.png"))); // NOI18N
        jBActividades.setText("Actividades");
        jBActividades.setColorHover(new java.awt.Color(43, 43, 43));
        jBActividades.setColorText(new java.awt.Color(154, 159, 168));
        jBActividades.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        jBActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActividadesActionPerformed(evt);
            }
        });
        jPanel2.add(jBActividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 285, 190, -1));

        jBperfil.setBackground(new java.awt.Color(0, 0, 0));
        jBperfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Perfil.png"))); // NOI18N
        jBperfil.setText("  Perfil");
        jBperfil.setColorHover(new java.awt.Color(43, 43, 43));
        jBperfil.setColorText(new java.awt.Color(154, 159, 168));
        jBperfil.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        jBperfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBperfilActionPerformed(evt);
            }
        });
        jPanel2.add(jBperfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 234, 190, -1));

        jLbrango.setBackground(new java.awt.Color(154, 159, 168));
        jLbrango.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLbrango.setForeground(new java.awt.Color(154, 159, 168));
        jLbrango.setText("Administrador");
        jPanel2.add(jLbrango, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, 25));

        jLbnombreemp.setBackground(new java.awt.Color(154, 159, 168));
        jLbnombreemp.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLbnombreemp.setForeground(new java.awt.Color(154, 159, 168));
        jLbnombreemp.setText("Bryan Hidalgo");
        jPanel2.add(jLbnombreemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 130, -1, 25));

        rSPanelCircle2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout rSPanelCircle2Layout = new javax.swing.GroupLayout(rSPanelCircle2);
        rSPanelCircle2.setLayout(rSPanelCircle2Layout);
        rSPanelCircle2Layout.setHorizontalGroup(
            rSPanelCircle2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );
        rSPanelCircle2Layout.setVerticalGroup(
            rSPanelCircle2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanel2.add(rSPanelCircle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 116, 110));

        rSPanelGradiente1.setColorPrimario(new java.awt.Color(102, 102, 102));
        rSPanelGradiente1.setColorSecundario(new java.awt.Color(0, 0, 0));

        jBtcerrarsesion.setBackground(new java.awt.Color(0, 0, 0));
        jBtcerrarsesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logout.png"))); // NOI18N
        jBtcerrarsesion.setText("Cerrar sesión");
        jBtcerrarsesion.setColorHover(new java.awt.Color(43, 43, 43));
        jBtcerrarsesion.setColorText(new java.awt.Color(154, 159, 168));
        jBtcerrarsesion.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N

        javax.swing.GroupLayout rSPanelGradiente1Layout = new javax.swing.GroupLayout(rSPanelGradiente1);
        rSPanelGradiente1.setLayout(rSPanelGradiente1Layout);
        rSPanelGradiente1Layout.setHorizontalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelGradiente1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBtcerrarsesion, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        rSPanelGradiente1Layout.setVerticalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelGradiente1Layout.createSequentialGroup()
                .addContainerGap(630, Short.MAX_VALUE)
                .addComponent(jBtcerrarsesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel2.add(rSPanelGradiente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 690));

        rSPanelsSlider1.setBackground(new java.awt.Color(255, 255, 255));

        pnl1.setBackground(new java.awt.Color(255, 255, 255));
        pnl1.setName("pnl1"); // NOI18N

        javax.swing.GroupLayout pnl1Layout = new javax.swing.GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnPerfil1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl1Layout.setVerticalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addComponent(pnPerfil1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        rSPanelsSlider1.add(pnl1, "card2");

        pnl3.setBackground(new java.awt.Color(255, 255, 255));
        pnl3.setName("pnl1"); // NOI18N

        javax.swing.GroupLayout pnl3Layout = new javax.swing.GroupLayout(pnl3);
        pnl3.setLayout(pnl3Layout);
        pnl3Layout.setHorizontalGroup(
            pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnVentas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnl3Layout.setVerticalGroup(
            pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl3Layout.createSequentialGroup()
                .addComponent(pnVentas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        rSPanelsSlider1.add(pnl3, "card2");

        pnl4.setBackground(new java.awt.Color(255, 255, 255));
        pnl4.setName("pnl2"); // NOI18N
        pnl4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnl4.add(jPregistros2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        rSPanelsSlider1.add(pnl4, "card3");

        pnl2.setBackground(new java.awt.Color(255, 255, 255));
        pnl2.setName("pnl2"); // NOI18N
        pnl2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnl2.add(jPactividades1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        rSPanelsSlider1.add(pnl2, "card3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(rSPanelsSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelsSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBreportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBreportesActionPerformed
        if(!this.jBreportes.isSelected()){
            this.jBperfil.setSelected(false);
            this.jBventas.setSelected(false);
            this.jBActividades.setSelected(false);
            this.jBreportes.setSelected(true);
            try {
                Factura cl = getfacturaSeleccionado();
                this.jPregistros2.llenarTabla(manager);
            } catch (DAOException ex) {
                Logger.getLogger(Empleado2.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Empleado2.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Empleado2.class.getName()).log(Level.SEVERE, null, ex);
            }
            rSPanelsSlider1.setPanelSlider(1, pnl4, RSPanelsSlider.DIRECT.RIGHT);
        }
    }//GEN-LAST:event_jBreportesActionPerformed

    private void jBventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBventasActionPerformed
        if(!this.jBventas.isSelected()){
            this.jBperfil.setSelected(false);
            this.jBventas.setSelected(true);
            this.jBActividades.setSelected(false);
            this.jBreportes.setSelected(false);
            try {
                Empleado em = getEmpleadoSeleccionado();
                pnVentas1.setEmpleado(em);
                pnVentas1.setManager(manager);
                pnVentas1.setEditable();
                pnVentas1.loadData();
            } catch (DAOException ex) {
                Logger.getLogger(Empleado2.class.getName()).log(Level.SEVERE, null, ex);
            }
            rSPanelsSlider1.setPanelSlider(1, pnl3, RSPanelsSlider.DIRECT.RIGHT);
        }
    }//GEN-LAST:event_jBventasActionPerformed

    private void jBActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActividadesActionPerformed
        if(!this.jBActividades.isSelected()){
            this.jBperfil.setSelected(false);
            this.jBventas.setSelected(false);
            this.jBActividades.setSelected(true);
            this.jBreportes.setSelected(false);
           
        }
        try {
                Empleado cl = getEmpleadoSeleccionado();
                this.jPactividades1.llenarTabla(manager, cl.getCod_empleado());
            } catch (DAOException ex) {
                Logger.getLogger(Empleado2.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Empleado2.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Empleado2.class.getName()).log(Level.SEVERE, null, ex);
            }

            rSPanelsSlider1.setPanelSlider(1, pnl2, RSPanelsSlider.DIRECT.RIGHT);
    }//GEN-LAST:event_jBActividadesActionPerformed

    private void jBperfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBperfilActionPerformed
        // TODO add your handling code here:
        if(!this.jBperfil.isSelected()){
            this.jBperfil.setSelected(true);
            this.jBventas.setSelected(false);
            this.jBActividades.setSelected(false);
            this.jBreportes.setSelected(false);
            rSPanelsSlider1.setPanelSlider(1, pnl1, RSPanelsSlider.DIRECT.RIGHT);
        }
    }//GEN-LAST:event_jBperfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empleado2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empleado2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empleado2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empleado2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        DAOManager manager = new OracleDaoManager("jdbc:oracle:thin:@localhost:1521:XE", "system", "042395");
        java.awt.EventQueue.invokeLater(() -> {
            try {
                Empleado2 dialog = new Empleado2(new javax.swing.JFrame(), true, manager);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            } catch (DAOException ex) {
                Logger.getLogger(Empleado2.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton jBActividades;
    private rojeru_san.RSButton jBperfil;
    private rojeru_san.RSButton jBreportes;
    private rojeru_san.RSButton jBtcerrarsesion;
    private rojeru_san.RSButton jBventas;
    private javax.swing.JLabel jLbnombreemp;
    private javax.swing.JLabel jLbrango;
    private pis.jPactividades jPactividades1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private pis.jPregistros jPregistros2;
    private pis.PnPerfil pnPerfil1;
    private pis.PnVentas pnVentas1;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl2;
    private javax.swing.JPanel pnl3;
    private javax.swing.JPanel pnl4;
    private rojeru_san.rspanel.RSPanelCircle rSPanelCircle2;
    private rspanelgradiente.RSPanelGradiente rSPanelGradiente1;
    private rojerusan.RSPanelsSlider rSPanelsSlider1;
    // End of variables declaration//GEN-END:variables
}
