/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pis;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import re.dao.DAOException;
import re.dao.DAOManager;
import re.dao.bd.OracleDaoManager;
import reg.modelo.Login;
import rojeru_san.*;
import rojerusan.*;


/**
 *
 * @author kriz_
 */
public class jDlgLogin extends javax.swing.JDialog {

    /**
     * Creates new form jDlgLogin
     */
    private DAOManager manager;
    private int cont;
    private String boton;

    public jDlgLogin(java.awt.Frame parent, boolean modal, DAOManager manager) {
        super(parent, modal);
        this.manager = manager;
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    public void setBoton(String boton) {
        this.boton = boton;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPasswordField2 = new RSMaterialComponent.RSPasswordIconUno();
        jBiniciarsesion = new rsbuttoncustom.RSButtonCustom();
        jTextField1 = new RSMaterialComponent.RSTextFieldOne();
        rSButtonCustom2 = new rojeru_san.rsbutton.RSButtonCustom();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Usuario");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contraseña");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 280, -1, 28));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/UserBW2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 33, 120, 150));

        jPasswordField2.setBackground(new java.awt.Color(45, 68, 100));
        jPasswordField2.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField2.setBorderColor(new java.awt.Color(255, 255, 255));
        jPasswordField2.setColorIcon(new java.awt.Color(255, 255, 255));
        jPasswordField2.setPhColor(new java.awt.Color(255, 255, 255));
        jPasswordField2.setPlaceholder("");
        jPanel1.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 320, 200, -1));

        jBiniciarsesion.setForeground(new java.awt.Color(88, 88, 88));
        jBiniciarsesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logout.png"))); // NOI18N
        jBiniciarsesion.setText("Iniciar sesion");
        jBiniciarsesion.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        jBiniciarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBiniciarsesionActionPerformed(evt);
            }
        });
        jPanel1.add(jBiniciarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 400, 160, 30));

        jTextField1.setBackground(new java.awt.Color(47, 75, 122));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorderColor(new java.awt.Color(255, 255, 255));
        jTextField1.setPhColor(new java.awt.Color(255, 255, 255));
        jTextField1.setPlaceholder("");
        jTextField1.setSelectionColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 230, 200, -1));

        rSButtonCustom2.setBackground(new java.awt.Color(207, 217, 242));
        rSButtonCustom2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/windowclose_104378.png"))); // NOI18N
        rSButtonCustom2.setColorMaterial(new java.awt.Color(207, 217, 242));
        rSButtonCustom2.setColorNoFocus(new java.awt.Color(207, 217, 242));
        rSButtonCustom2.setOpaque(true);
        rSButtonCustom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonCustom2ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonCustom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 3, 40, 20));

        jLabel2.setBackground(new java.awt.Color(207, 217, 242));
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 23));

        jLabel3.setBackground(new java.awt.Color(47, 75, 122));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Playas.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 0, 700, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBiniciarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBiniciarsesionActionPerformed
         // TODO add your handling code here:
        try {
            Login login = manager.getLoginDAO().obtenerUser(jTextField1.getText());
            try {
                if (login.getUsuario().equals(jTextField1.getText()) && login.getContraseña().equals(String.valueOf(jPasswordField2.getPassword()))) {

                    DAOManager manager = new OracleDaoManager("jdbc:oracle:thin:@localhost:1521:XE", "system", "042395");
                    int cod = 0;
                    if (login.getIdUsuario() != 0 && boton.equals("Usuario")) {
                        cod = login.getIdUsuario();
                        jDialPerfil ventana = new jDialPerfil(null, true, manager, cod, login.getUsuario());
                        dispose();
                        ventana.pack();
                        ventana.setVisible(true);
                    } else if (login.getIdEmpleado() != 0 && boton.equals("Empleado")) {
                        cod = login.getIdEmpleado();
                        Empleado2 ventana = new Empleado2(null, true, manager, cod, login.getUsuario());                      
                        dispose();
                        ventana.pack();
                        ventana.setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(null, "No tiene permisos para entrar al perfil deseado", "Sistema", JOptionPane.ERROR_MESSAGE);
                        jFrmPrincipal ventana = new jFrmPrincipal();
                        dispose();
                        ventana.setVisible(true);
                    }
                } else {
                    cont = cont + 1;
                    JOptionPane.showMessageDialog(null, "Contraseña Incorrecta.\nLe quedan " + (3 - cont) + " intentos", "Sistema", JOptionPane.ERROR_MESSAGE);
                    if (cont == 3) {
                        jFrmPrincipal ventana = new jFrmPrincipal();
                        dispose();
                        ventana.setVisible(true);
                    }

                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(jFrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(jFrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (Exception ex) {
        }                             
    }//GEN-LAST:event_jBiniciarsesionActionPerformed

    private void rSButtonCustom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonCustom2ActionPerformed
        dispose();
    }//GEN-LAST:event_rSButtonCustom2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, SQLException{
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jDlgLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jDlgLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jDlgLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jDlgLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    DAOManager manager = new OracleDaoManager("jdbc:oracle:thin:@localhost:1521:XE", "system", "042395");
                    jDlgLogin dialog = new jDlgLogin(new javax.swing.JFrame(), true, manager);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(jDlgLogin.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(jDlgLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttoncustom.RSButtonCustom jBiniciarsesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private RSMaterialComponent.RSPasswordIconUno jPasswordField2;
    private RSMaterialComponent.RSTextFieldOne jTextField1;
    private rojeru_san.rsbutton.RSButtonCustom rSButtonCustom2;
    // End of variables declaration//GEN-END:variables

}
