/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pis;

/**
 *
 * @author Astaroth
 */
public class jPregistros extends javax.swing.JPanel {

    /**
     * Creates new form jPactividades
     */
    public jPregistros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelVector2 = new rojeru_san.rspanel.RSPanelVector();
        rSLabelHora1 = new rojeru_san.rsdate.RSLabelHora();
        rSLabelFecha1 = new rojeru_san.RSLabelFecha();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rSPanelVector3 = new rojeru_san.rspanel.RSPanelVector();
        jBtventasgenerar = new rojeru_san.rsbutton.RSButtonRound();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableregisventas = new rojerusan.RSTableMetro1();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelVector2.setBackground(new java.awt.Color(168, 234, 82));
        rSPanelVector2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSLabelHora1.setBackground(new java.awt.Color(0, 0, 0));
        rSLabelHora1.setForeground(new java.awt.Color(51, 51, 51));
        rSPanelVector2.add(rSLabelHora1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1061, 0, 81, 29));

        rSLabelFecha1.setForeground(new java.awt.Color(51, 51, 51));
        rSPanelVector2.add(rSLabelFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(978, 2, 79, 27));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Date:");
        rSPanelVector2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(939, 2, -1, 27));

        jLabel2.setFont(new java.awt.Font("Trajan Pro", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Registro de ventas");
        rSPanelVector2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        jLabel8.setFont(new java.awt.Font("Trajan Pro", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Registro.png"))); // NOI18N
        rSPanelVector2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        rSPanelVector3.setBackground(new java.awt.Color(188, 38, 28));
        rSPanelVector3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtventasgenerar.setBackground(new java.awt.Color(51, 51, 51));
        jBtventasgenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/register-machine_icon-icons.com_48487.png"))); // NOI18N
        jBtventasgenerar.setText("Generar");
        jBtventasgenerar.setColorBorde(new java.awt.Color(43, 43, 43));
        jBtventasgenerar.setColorHover(new java.awt.Color(102, 102, 102));
        jBtventasgenerar.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        rSPanelVector3.add(jBtventasgenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 15, 160, -1));

        rSPanelVector2.add(rSPanelVector3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 900, 70));

        jTableregisventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableregisventas.setBackgoundHead(new java.awt.Color(51, 51, 51));
        jTableregisventas.setBackgoundHover(new java.awt.Color(121, 116, 210));
        jTableregisventas.setColorPrimaryText(new java.awt.Color(121, 116, 210));
        jTableregisventas.setColorSecundaryText(new java.awt.Color(121, 116, 210));
        jTableregisventas.setOpaque(false);
        jTableregisventas.setSelectionBackground(new java.awt.Color(121, 116, 210));
        jScrollPane2.setViewportView(jTableregisventas);

        rSPanelVector2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 700, 420));

        add(rSPanelVector2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 690));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.rsbutton.RSButtonRound jBtventasgenerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private rojerusan.RSTableMetro1 jTableregisventas;
    private rojeru_san.RSLabelFecha rSLabelFecha1;
    private rojeru_san.rsdate.RSLabelHora rSLabelHora1;
    private rojeru_san.rspanel.RSPanelVector rSPanelVector2;
    private rojeru_san.rspanel.RSPanelVector rSPanelVector3;
    // End of variables declaration//GEN-END:variables
}
