/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pis;

import java.sql.SQLException;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import re.dao.DAOException;
import re.dao.DAOManager;
import re.dao.bd.OracleDaoManager;
import reg.modelo.Prueb;

/**
 *
 * @author kriz_
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private DAOManager manager;

    public NewJFrame(DAOManager manager) throws DAOException {
        initComponents();
        this.manager = manager;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        date = new rojerusan.RSDateChooser();
        rSButtonCircle1 = new rojerusan.RSButtonCircle();
        rSPassView1 = new rojeru_san.rsfield.RSPassView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        date.setFormatoFecha("dd/MM/yyyy");
        date.setLimpiarFecha(false);
        date.setPlaceholder("xd");
        date.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dateFocusLost(evt);
            }
        });

        rSButtonCircle1.setText("rSButtonCircle1");
        rSButtonCircle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonCircle1ActionPerformed(evt);
            }
        });

        rSPassView1.setText("rSPassView1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rSPassView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(214, 214, 214)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(106, 106, 106)
                            .addComponent(rSButtonCircle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSPassView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(rSButtonCircle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dateFocusLost
        // TODO add your handling code here:
        if (date.getTextoFecha() == null) {
            System.out.println("xd");
        } else {
            DateTimeFormatter date1 = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate fechanacimiento = LocalDate.parse(date.getTextoFecha(), date1);
            LocalDate fechaactual = LocalDate.now();

            Period periodo = Period.between(fechanacimiento, fechaactual);

            System.out.println("Tienes " + periodo.getYears() + " años con " + periodo.getMonths() + " meses y " + periodo.getDays() + " dias");
        }
    }//GEN-LAST:event_dateFocusLost

    private void rSButtonCircle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonCircle1ActionPerformed
        try {
            // TODO add your handling code here:
            if (date.getFechaSeleccionada().isEmpty()) {
                System.out.println("xd");
            } else {
                DateTimeFormatter date1 = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                LocalDate fechanacimiento = LocalDate.parse(date.getFechaSeleccionada(), date1);
                LocalDate fechaactual = LocalDate.now();
                String xd=fechaactual.format(date1);
                System.out.println(xd);
                Period periodo = Period.between(fechanacimiento, fechaactual);
                if (periodo.getYears() <= 0 && periodo.getMonths() <= 0 && periodo.getDays() <= 0) {
                    System.out.println("No te pases hombre escoje bien");
                } else {
                    if (periodo.getYears() >= 18) {
                        System.out.println("Eres mayor de edad");
                    } else {
                        System.out.println("Aun eres peque;in xd");
                    }

//            System.out.println("Tienes "+periodo.getYears()+" años con "+periodo.getMonths()+" meses y "+periodo.getDays()+" dias");
                }
            }
            Prueb pr = new Prueb(2, date.getFechaSeleccionada());
            manager.getPruebDAO().insertar(pr);
        } catch (DAOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rSButtonCircle1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        DAOManager manager = new OracleDaoManager("jdbc:oracle:thin:@localhost:1521:XE", "system", "042395");
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new NewJFrame(manager).setVisible(true);
            } catch (DAOException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSDateChooser date;
    private rojerusan.RSButtonCircle rSButtonCircle1;
    private rojeru_san.rsfield.RSPassView rSPassView1;
    // End of variables declaration//GEN-END:variables
}
